title = 'dale.emery.name'
copyright = '© 2003–2023 Dale H. Emery'
baseURL = 'https://dale.emery.name'

languageCode = 'en-us'
theme = 'Dale'

[taxonomies]
tag = 'tags'

[markup.goldmark.renderer]
unsafe = true

